dist: xenial
sudo: required
language: python
before_install:
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
install:
  - sudo apt-get install software-properties-common
  - sudo apt-get -y install ansible
  - ansible --version
script:
  - ./scripts/create_new_environment.sh environments/local
  - echo "localhost ansible_host=localhost" > environments/local/inventory
  - echo "" >> environments/local/inventory
  - echo "[sympa]" >> environments/local/inventory
  - echo "localhost" >> environments/local/inventory
  - ansible-playbook site.yml --connection=local --become -i environments/local/inventory
services:
  - mysql
