- name: Check Sympa tar.gz existence
  stat: path="{{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}.tar.gz"
  register: sympa_archive_file

- name: Download Sympa tar.gz
  get_url:
    url: "{{ sympa_download_url }}"
    dest: "{{ sympa_install_prefix }}/src"
    sha256sum: "{{ sympa_sha256[sympa_version] }}"
  when: not sympa_archive_file.stat.exists

- name: Create the Sympa src directory
  file: path={{ sympa_install_prefix }}/src/sympa-{{ sympa_version }} state=directory
  
- name: Unpack the tarball
  unarchive: src={{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}.tar.gz dest={{ sympa_install_prefix }}/src/ copy=no creates={{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}/README

- name: Apply Sympa patches
  patch:
    src: "{{ item }}"
    basedir: "{{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}"
    strip: 1
  when: sympa_apply_patches
  with_fileglob: "{{ role_path }}/patches/{{ sympa_version }}/*.diff"

