---
- name: Install list aliases file
  copy:
    src: files/list_aliases.tt2
    dest: "{{ install_prefix }}/{{ sympa.install_dir_name }}/etc/list_aliases.tt2"
    owner: sympa
    group: sympa
    mode: 0644

- name: Creating Sympa aliases file (1/2)
  file:
    path: "{{ sympa.mail.alias_directory }}"
    state: directory
    owner: sympa
    group: sympa
    mode: 0755

- name: Creating Sympa aliases file (2/2)
  file:
    path: "{{ sympa.mail.alias_directory }}/{{ item }}"
    state: touch
    owner: sympa
    group: sympa
    mode: 0644
  with_items:
    - "{{ sympa.mail.alias_file }}"
    - "{{ sympa.mail.alias_file }}.db"

- name: Compiling sympa_aliases
  command: "postmap {{ sympa.mail.alias_directory }}/{{ sympa.mail.alias_file }}"

- name: Adding list domains as virtual domains
  blockinfile:
    path: /etc/postfix/domains.sympa
    create: yes
    state: present
    marker: "# {mark} ANSIBLE MANAGED {{ item }} domain"
    block: |
      {{ item }}                # {{ item }} is a mailing list domain.
  with_items: "{{ mail_domains }}"

- name: Compiling Sympa transport
  command: postmap /etc/postfix/domains.sympa

- name: Adding required generic aliases
  blockinfile:
    path: /etc/postfix/virtual.sympa
    create: yes
    state: present
    marker: "# {mark} ANSIBLE MANAGED {{ item }} aliases"
    block: |
      sympa-request@{{ item }}  postmaster@localhost
      sympa-owner@{{ item }}    postmaster@localhost
  with_items: "{{ mail_domains }}"

- name: Compiling Sympa transport
  command: postmap /etc/postfix/virtual.sympa

- name: Adding required generic transports
  blockinfile:
    path: /etc/postfix/transport
    create: yes
    state: present
    marker: "# {mark} ANSIBLE MANAGED {{ item }} transports"
    block: |
      sympa@{{ item }}          sympa:sympa@{{ item }}
      listmaster@{{ item }}     sympa:listmaster@{{ item }}
      bounce@{{ item }}         sympabounce:sympa@{{ item }}
      abuse-feedback-report@{{ item }}  sympabounce:sympa@{{ item }}
  with_items: "{{ mail_domains }}"

- name: Compiling Sympa transport
  command: postmap /etc/postfix/transport

- name: Setting up main.cf
  blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} ANSIBLE MANAGED sympa configuration"
    block: |
      virtual_mailbox_domains =
        hash:/etc/postfix/domains.sympa
      virtual_mailbox_maps =
        hash:/etc/postfix/transport,
        hash:/etc/postfix/virtual.sympa,
        hash:{{ sympa.mail.alias_directory }}/{{ sympa.mail.alias_file }}
      virtual_alias_maps =
        hash:/etc/postfix/virtual.sympa
      transport_maps =
        hash:/etc/postfix/transport,
        hash:/etc/postfix/virtual.sympa,
        hash:{{ sympa.mail.alias_directory }}/{{ sympa.mail.alias_file }}
  notify: restart postfix

