---

- name: restart netfilter-persistent
  service: name=netfilter-persistent state=reloaded

- name: restart ntpd
  service: name=ntpd state=restarted

# Include handlers for environment specific tasks
- include: "{{ inventory_dir }}/handlers/common.yml"