---

- name: restart netfilter-persistent
  service: name=netfilter-persistent state=reloaded

- name: restart ntpd
  service: name=ntpd state=restarted

- name: restart sshd
  service: name=ssh state=restarted
